# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-07 18:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_auto_20170207_2026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_model',
            name='assign_date',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='order_model',
            name='client_deadline',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='order_model',
            name='payment_date',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='order_model',
            name='send_date',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='order_model',
            name='writer_deadline',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
