# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-07 18:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_remove_order_model_client_num_of_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order_model',
            old_name='writer',
            new_name='writer_name',
        ),
        migrations.AddField(
            model_name='order_model',
            name='client_num_of_order',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
