# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-07 18:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_auto_20170207_2045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_model',
            name='writer_name',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
