# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-15 11:02
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app1', '0006_auto_20170207_2046'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_model',
            name='writer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
