# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-15 14:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_order_model_writer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_model',
            name='status',
            field=models.CharField(blank=True, default='available', max_length=300),
        ),
    ]
