# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-07 13:30
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app1', '0008_auto_20170215_1600'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app1.Order_model')),
                ('writers', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
