# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-12 11:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0013_auto_20170312_1343'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='order_file',
            field=models.FileField(blank=True, upload_to='order_files/%Y/%m/%d'),
        ),
    ]
