# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-12 14:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0014_comment_order_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='create_date',
            field=models.DateTimeField(null=True),
        ),
    ]
