# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-12 14:35
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0015_comment_create_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2000, 1, 1, 1, 1, 1, 1)),
        ),
    ]
