# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-17 13:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0016_auto_20170312_1635'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='order_file',
        ),
    ]
