# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-18 20:28
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app1', '0017_remove_comment_order_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_file', models.FileField(upload_to='order_files/%Y/%m/%d')),
                ('create_date', models.DateTimeField(default=datetime.datetime(2000, 1, 1, 1, 1, 1, 1))),
                ('is_final', models.BooleanField(default=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.Order_model')),
            ],
        ),
    ]
