# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-28 18:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0019_remove_order_model_order_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_model',
            name='controller',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.UserProfile'),
        ),
    ]
