# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-10 16:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0020_order_model_controller'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_model',
            name='times_returned_for_revision',
            field=models.IntegerField(default=0),
        ),
    ]
