# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-25 16:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0022_userprofile_rejected_orders'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='rejected_orders',
        ),
    ]
