# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-28 09:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0024_rejection'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rejection',
            old_name='writer',
            new_name='rejector',
        ),
    ]
