# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-28 09:50
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0025_auto_20170828_0946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rejection',
            name='rejector',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
